import os

HOMESERVER_URL = os.environ["HOMESERVER_URL"]
MAUTRIX_TELEGRAM_DB = os.environ["MAUTRIX_TELEGRAM_DB"]
MAUTRIX_SIGNAL_DB = os.environ["MAUTRIX_SIGNAL_DB"]
MAUTRIX_WHATSAPP_DB = os.environ["MAUTRIX_WHATSAPP_DB"]
MAUTRIX_DISCORD_DB = os.environ["MAUTRIX_DISCORD_DB"]
SYNAPSE_DB = os.environ["SYNAPSE_DB"]
SYNAPSE_ADMIN_KEY = os.environ["SYNAPSE_ADMIN_KEY"]
